table Customer
	lineageTag: cecc91a6-a6e6-4d49-b44d-f339327d273f

	column CustomerId
		dataType: int64
		formatString: 0
		lineageTag: b4f8f297-4692-47b5-ba77-303bf0c5dfe3
		summarizeBy: none
		sourceColumn: CustomerId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		isHidden
		lineageTag: 2f02b2bb-14b7-4cc8-bcc6-2ecbc966fb2c
		summarizeBy: none
		sourceColumn: Company

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		isHidden
		lineageTag: 735940f2-9fd0-4272-a0fb-e83009b05ac9
		summarizeBy: none
		sourceColumn: Address

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		isHidden
		lineageTag: c845cc88-f2a1-488f-ae40-6bd59331aa47
		summarizeBy: none
		sourceColumn: City

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		isHidden
		lineageTag: 9133a423-719c-482d-b1fd-b4164589a728
		summarizeBy: none
		sourceColumn: State

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 958f1750-ca9e-4294-a176-446c00e72279
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PostalCode
		dataType: string
		lineageTag: 00c71b4a-79c5-49e9-bfbf-3be94c39006d
		summarizeBy: none
		sourceColumn: PostalCode

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 08c65249-4b2e-4c48-a802-6a577f67bd04
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Fax
		dataType: string
		isHidden
		lineageTag: 0544a146-d1a6-4d60-b330-fc5a58e3211c
		summarizeBy: none
		sourceColumn: Fax

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 77c6a9bc-7123-4ea9-9701-1abdf34a2333
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column SupportRepId
		dataType: int64
		formatString: 0
		lineageTag: 375adcce-83fb-4764-8f77-36d86299d743
		summarizeBy: none
		sourceColumn: SupportRepId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 8dbc1280-b5b7-4a8c-bd84-416b8e46591f
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		source =
				let
				    Source = Source,
				    #"D:\Nasif Azam\Music Sales\_Customer csv" = Source{[#"Folder Path"="D:\Nasif Azam\Music Sales\Datasets\",Name="Customer.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"D:\Nasif Azam\Music Sales\_Customer csv",[Delimiter=",", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerId", Int64.Type}, {"FirstName", type text}, {"LastName", type text}, {"Company", type text}, {"Address", type text}, {"City", type text}, {"State", type text}, {"Country", type text}, {"PostalCode", type text}, {"Phone", type text}, {"Fax", type text}, {"Email", type text}, {"SupportRepId", Int64.Type}}),
				    #"Merged Columns" = Table.CombineColumns(#"Changed Type",{"FirstName", "LastName"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"CustomerName")
				in
				    #"Merged Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

